<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All Tests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-24T10:20:24</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>fe2bcd78-c1a2-4a96-8f22-0ccf82e9f566</testSuiteGuid>
   <testCaseLink>
      <guid>def7c0cc-9cf0-45ad-9a38-f54175b62d72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Simple Examples/Create Issue Test/Test step with custom keyword/Create Issue with specified information</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>edffee0f-bbfb-4a80-859a-fd4cc2083fab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Simple Examples/Login Test/Test steps which calls from other test cases/Login with username and password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56bc4b41-5971-4f6a-984e-676c745ace04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a62d29a2-eef4-440c-98e9-97975a229986</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>01a5a6cb-7a3c-4ac2-a7f0-0a922f7da9f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Simple Examples/Login Test/Test steps which calls from other test cases/Login successfully with username and password</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1a92bf49-59ec-4c3a-b7f2-2e3060349e69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Simple Examples/Login Test/Test data from GlobalVariable examples/Login with username and encrypted password specified in GlobalVariable</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6beea1e1-3578-4534-88b1-fab19e7044fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Simple Examples/Login Test/Test data from GlobalVariable examples/Login with username and password specified in GlobalVariable</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c6ebe980-92cf-4468-b327-46145b3f2cba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Simple Examples/Login Test/Test data hardcoding examples/Login with username and password specified in the test steps</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>54c40be2-0025-4a49-95c6-a06a9c84d3a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Simple Examples/Login Test/Data-driven examples/Login with username and password as a default value of variables</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a11316c-738f-4e70-a8b5-63aaf81e1d91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>deb3cf4c-1dee-42c6-ab83-fae4778b5936</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>498af31c-8bd1-4891-ad0d-df4306a8ab9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Simple Examples/Login Test/Data-driven examples/Login with username and password as variables passed by data-files</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdde4842-9fe3-4fb6-9c10-485c3a78a9dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7934176c-9dd2-4059-9914-100665990135</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec3e4c74-092b-4b5d-b8a7-c13a455dd911</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Create Issue Test/User should be able to create issue successfully</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85a603bc-fc08-4ed2-bcb5-3c52d620cff9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec627c4c-6549-4a01-b9e2-605be351dd4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bba64aa6-0c6f-48f6-9c70-e9b5c15d2110</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3420820c-45c5-4cf3-a50f-05ec17025041</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cba50a02-866d-4cec-8ae2-76f54a55bb74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e536bdb8-60f4-46bf-aded-48ef2d54ab49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Create Issue Test/User should be able to create issue successfully - Copy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>069d7e85-e542-4883-8b95-d670611460b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acc2b70d-ec6d-446f-bde6-2af85236c519</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03d8b678-3744-48fe-b84f-ac3b7e3ce82b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7025da6b-46e1-43ca-bff1-75fb933b89a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25c3b66d-019e-405c-bacd-a142fe2c28ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6af284f9-7f9a-43a0-88cc-88f04757b8df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Search Issue Test/User should be able to search and verify issue content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f7d9b1f-ce67-405f-a886-85b26f22388a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1166b920-d85c-4cc3-9b84-452dca5f9e39</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f3ed4c2-990a-43db-9cc4-d27f11c4621e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Search Issue Test/User should be able to search issues with an jql</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff616f97-8cc9-414d-939a-b6878e3db8fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d72fdf9a-e248-4c87-9d3b-4a2df10902c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Login Test/User should login successfully using encrypted password</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>21360740-2f83-4df8-bc20-dda95abdc536</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Login Test/User should login successfully with a valid account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db0d2634-eb7c-41f6-900b-212e3b6baa42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5ee436b-09a4-4881-bfb1-21ebd667f963</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
